GET {{API_URL}}/boards HTTP/1.1
Accept: application/json

###

POST {{API_URL}}/boards HTTP/1.1
Content-Type: application/json

{
  "name": "Joe Doe"
}

> {%
  const data = JSON.parse(response.body);
  client.global.set("UUID", data.uuid);
%}

###

GET {{API_URL}}/boards/{{UUID}} HTTP/1.1
Accept: application/json

###

PUT {{API_URL}}/boards/{{UUID}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "Buy milk",
  "status": "Done"
}

> {%
  const data = JSON.parse(response.body);
  client.global.set("UUID", data.uuid);
%}

###

DELETE {{API_URL}}/boards/{{UUID}} HTTP/1.1
Accept: application/json
