GET {{API_URL}}/lists HTTP/1.1
Accept: application/json

###

POST {{API_URL}}/lists HTTP/1.1
Content-Type: application/json

{
  "name": "Joe Doe",
  "board_uuid": "8a45e6ba-709f-413e-a480-2142a06d5c1a"
}

> {%
  const data = JSON.parse(response.body);
  client.global.set("UUID", data.uuid);
%}

###

GET {{API_URL}}/lists/{{UUID}} HTTP/1.1
Accept: application/json

###

PUT {{API_URL}}/lists/{{UUID}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "Buy milk",
  "status": "Done"
}

> {%
  const data = JSON.parse(response.body);
  client.global.set("UUID", data.uuid);
%}

###

DELETE {{API_URL}}/lists/{{UUID}} HTTP/1.1
Accept: application/json
