@api = {{API_URL}} 

###

GET {{api}}/lists HTTP/1.1
Accept: application/json

###

POST {{api}}/lists HTTP/1.1
Content-Type: application/json

{
  "name": "Joe Doe",
  "board_uuid": "{{board_uuid}}" 
}

# @lang lua
> {%
  local body = vim.fn.json_decode(response.body)
  client.global.set("list_uuid", body["uuid"])
%}

###

GET {{api}}/lists/{{list_uuid}} HTTP/1.1
Accept: application/json

###

PUT {{api}}/lists/{{list_uuid}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "Buy milk",
  "status": "Done"
}

###

DELETE {{api}}/lists/{{list_uuid}} HTTP/1.1
Accept: application/json

###

GET {{api}}/lists/{{lists_uuid}}/tasks HTTP/1.1
Accept: application/json

