@api = {{API_URL}} 

###

GET {{api}}/tasks HTTP/1.1
Accept: application/json

###

POST {{api}}/tasks HTTP/1.1
Content-Type: application/json

{
  "status": "Todo",
  "priority": "Medium",
  "name": "Joe Doe",
  "position": 1,
  "list_uuid": "{{list_uuid}}"
}

# @lang lua
> {%
  local body = vim.fn.json_decode(response.body)
  client.global.set("task_uuid", body["uuid"])
%}

###

GET {{api}}/tasks/{{task_uuid}} HTTP/1.1
Accept: application/json

###

PUT {{api}}/tasks/{{task_uuid}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "Buy milk",
  "status": "Done",
  "position": null,
  "description": null
}

###

DELETE {{api}}/tasks/{{task_uuid}} HTTP/1.1
Accept: application/json
